Assignment:	 
		g++ model.cpp -c -std=c++0x
		g++ controller.cpp -c
		g++ view.cpp -c
		g++ FastTrackball.c -c
		g++ FastTrackball.o controller.o view.o model.o Main.cpp -o  assignment3 -lSOIL -lglut -lGLU -lGL -std=c++0x

run:
		./assignment3 ../bin/apple.ply ../bin/canstick.ply
clear:
		rm -f assignment3
		rm *.o
